#include "ofTemplateMake.h"
#include "addons.h"
#include <fstream>


void ofTemplateMake::load() {
	alert("ofTemplateMake::load()", 92);

	copyTemplateFiles.push_back({ path / "config.make",
		conf.projectPath / "config.make" });

	for (auto & l : conf.nodeToStrings("make")) {
		copyTemplateFiles.back().appends.emplace_back(l);
		// alert(l, 35);
	}

	copyTemplateFiles.push_back({ path / "Makefile",
		conf.projectPath / "Makefile" });
}

void ofTemplateMake::save() {
	alert("ofTemplateMake::save()", 92);
	if (conf.addons.size()) {
		alert(" saving addons.make", 2);
		fs::path fileName { conf.projectPath / "addons.make" };
		std::ofstream addonsMake(fileName);
		for (auto & a : conf.addons) {
			if (!a->isProject) {
				addonsMake << a->name << std::endl;
			}
		}
		addonsMake.close();
	}

	if (conf.defines.size() || conf.additionalSources.size()) {
		std::string allDefines { "# Generated by " + getVersion() };
		if (conf.defines.size()) {
			// alert("PROJECT_DEFINES", 95);
			allDefines += "\nPROJECT_DEFINES =";
			for (auto & d : conf.defines) {
				allDefines += " " + d;
			}
		}
		if (conf.additionalSources.size()) {
			allDefines += "\nPROJECT_EXTERNAL_SOURCE_PATHS =";
			for (auto & d : conf.additionalSources) {
				allDefines += " " + d.string();
			}
		}
		copyTemplateFiles[0].appends.emplace_back(allDefines);
	}
}
