name: OF

on:
  push:
    paths-ignore:
      # - "ofGen/*"
      - "**/*.md"
      - "**/*.txt"
      - "examples/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  ccache: ccache

jobs:
  ofworks:
    strategy:
      matrix:
        cfg:
          - { os: macos-latest }
          - { os: ubuntu-latest }
    runs-on: ${{ matrix.cfg.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Brew
        if: matrix.cfg.os == macos-latest
        uses: tecolicom/actions-use-homebrew-tools@v1.3
        with:
          tools: wget2 yaml-cpp fmt ccache nlohmann-json # fmt

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.17
        with:
          key: ${{ matrix.cfg.platform }}-${{ matrix.cfg.target }}

      - name: Libs
        run: ./libs/libs.sh

      - name: ofGen
        run: |
          cd ofGen
          ./compile.sh
          ./install.sh

      - name: XCodebuild Core
        if: matrix.cfg.os == macos-latest
        run: |
          cd libs/openFrameworksCompiled/project/macos
          xcodebuild -arch arm64

      - name: Make OF Core
        run: |
          cd libs/openFrameworksCompiled/project/
          make -j Debug

      - name: All Addons Example
        run: |
          cd examples/templates/allAddonsExample
          ofGen buildrun
          # xcodebuild -arch arm64

      - name: Tests
        run: ./scripts/macos/tests.sh
