name: OF

on:
  push:
    paths-ignore:
      - "ofGen/*"
      - "**/*.md"
      - "**/*.txt"
      - "examples/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  ccache: ccache
  RELEASE: latest

jobs:
  build-macos:
    # runs-on: macos-latest
    runs-on: macos-15
    strategy:
      matrix:
        cfg:
          - { target: macos, opt: "xcode" }
          # - { target: osx, opt: "makefiles" }
    steps:
      - uses: actions/checkout@v4

      - name: Brew
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: wget2 fmt yaml-cpp

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.14
        with:
          key: ${{ matrix.cfg.target }}-${{ matrix.cfg.opt }}

      - name: Libs
        # run: ./scripts/macos/libs.sh
        run: ./libs.sh

      - name: XCodebuild
        # run: ./scripts/macos/libs.sh
        run: |
          cd libs/openFrameworksCompiled/project/macos
          xcodebuild -arch arm64

      - name: Make OF Core
        # run: ./scripts/macos/libs.sh
        run: |
          cd libs/openFrameworksCompiled/project/
          make -j

      - name: Tests
        run: ./scripts/macos/tests.sh

      - name: ofGen
        run: |
          ./ofGen/compile.sh
          ./ofGen/ofGen

#       - name: Build
#         run: if [ ${{ matrix.cfg.opt }} = "xcode" ]; then
#           scripts/ci/${{ matrix.cfg.target }}/build.sh ${{ matrix.cfg.opt }};
#           else
#           scripts/ci/${{ matrix.cfg.target }}/run_tests.sh;
#           fi
#         env:
#           DEVELOPER_DIR: "/Applications/Xcode.app/Contents/Developer"
#           SDKROOT: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
# # - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
